# Generated by Django 3.1.6 on 2021-02-20 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonnumber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='commonnumber',
            name='teerresult',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commonnumber.teerresult'),
        ),
        migrations.AddField(
            model_name='teerresult',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='commonnumber',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teerresult',
            name='resultdate',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commonnumber.resultdate'),
        ),
    ]
