# Generated by Django 3.1.6 on 2021-02-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonnumber', '0002_auto_20210221_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonnumber',
            name='teerresult',
        ),
        migrations.RemoveField(
            model_name='teerresult',
            name='resultdate',
        ),
        migrations.AddField(
            model_name='teerresult',
            name='commonnumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='ResultDate',
        ),
    ]
